#!/usr/bin/env python3
"""Build the one canonical closed path used by both simulated vehicles.

The source recording contains a good lap followed by a short run past the
start line.  This tool detects the return to the start, removes that tail,
joins the two observations of the start, lightly smooths the periodic seam,
and resamples the result at uniform arc length.

The CSV is the ROSbot input.  The NPY contains the exact same x/y/yaw plus
curvature for QCar MPC.  Keeping both files generated by this one command
prevents the two vehicles from silently following different geometry.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import tempfile

import numpy as np


DEFAULT_SPACING_M = 0.05
DEFAULT_TAIL_SEARCH_FRACTION = 0.75
MAX_SEAM_DETECTION_GAP_M = 0.15
PERIODIC_SMOOTHING_PASSES = 5


def load_recorded_csv(path: str) -> np.ndarray:
    with open(path, "r", encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream)
        if not reader.fieldnames or not {"x", "y"}.issubset(reader.fieldnames):
            raise RuntimeError("recorded path CSV must contain x and y columns")
        points = [[float(row["x"]), float(row["y"])] for row in reader]

    xy = np.asarray(points, dtype=float)
    if xy.ndim != 2 or xy.shape[0] < 20 or xy.shape[1] != 2:
        raise RuntimeError("recorded path must contain at least 20 x/y points")
    if not np.all(np.isfinite(xy)):
        raise RuntimeError("recorded path contains non-finite values")
    return xy


def find_return_to_start(
    xy: np.ndarray,
    search_fraction: float = DEFAULT_TAIL_SEARCH_FRACTION,
) -> tuple[int, float]:
    """Return the late-lap point nearest the first recorded position."""
    if not 0.5 <= search_fraction < 1.0:
        raise ValueError("tail search fraction must be in [0.5, 1.0)")

    search_start = max(3, int(math.floor(len(xy) * search_fraction)))
    distances = np.linalg.norm(xy[search_start:] - xy[0], axis=1)
    seam_index = search_start + int(np.argmin(distances))
    seam_gap = float(distances[seam_index - search_start])
    if seam_gap > MAX_SEAM_DETECTION_GAP_M:
        raise RuntimeError(
            f"recording never returns to its start: closest late point is "
            f"{seam_gap:.3f} m away (limit {MAX_SEAM_DETECTION_GAP_M:.3f} m)"
        )
    return seam_index, seam_gap


def resample_closed(xy_closed: np.ndarray, spacing_m: float) -> np.ndarray:
    """Uniformly resample a closed polyline without duplicating its endpoint."""
    if spacing_m <= 0.0:
        raise ValueError("spacing must be positive")
    if not np.allclose(xy_closed[0], xy_closed[-1], atol=1e-12, rtol=0.0):
        raise ValueError("closed resampling requires equal first/last points")

    segment_lengths = np.linalg.norm(np.diff(xy_closed, axis=0), axis=1)
    if np.any(segment_lengths < 1e-6):
        raise RuntimeError("closed source path contains duplicate adjacent points")
    cumulative = np.concatenate(([0.0], np.cumsum(segment_lengths)))
    total_length = float(cumulative[-1])
    point_count = max(3, int(round(total_length / spacing_m)))
    samples = np.arange(point_count, dtype=float) * total_length / point_count
    return np.column_stack(
        (
            np.interp(samples, cumulative, xy_closed[:, 0]),
            np.interp(samples, cumulative, xy_closed[:, 1]),
        )
    )


def smooth_periodic_once(xy: np.ndarray) -> np.ndarray:
    """A small periodic binomial filter (approximately sigma=one sample)."""
    return (
        np.roll(xy, 2, axis=0)
        + 4.0 * np.roll(xy, 1, axis=0)
        + 6.0 * xy
        + 4.0 * np.roll(xy, -1, axis=0)
        + np.roll(xy, -2, axis=0)
    ) / 16.0


def periodic_geometry(xy: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return unwrapped tangent yaw and curvature magnitude for a loop."""
    previous = np.roll(xy, 1, axis=0)
    following = np.roll(xy, -1, axis=0)
    derivative = 0.5 * (following - previous)
    second_derivative = following - 2.0 * xy + previous

    yaw = np.unwrap(np.arctan2(derivative[:, 1], derivative[:, 0]))
    denominator = np.power(np.sum(derivative * derivative, axis=1), 1.5)
    denominator = np.maximum(denominator, 1e-9)
    signed_curvature = (
        derivative[:, 0] * second_derivative[:, 1]
        - derivative[:, 1] * second_derivative[:, 0]
    ) / denominator
    curvature = np.abs(np.nan_to_num(signed_curvature))
    return yaw, curvature


def build_canonical_path(
    recorded_xy: np.ndarray,
    spacing_m: float = DEFAULT_SPACING_M,
) -> tuple[np.ndarray, dict]:
    seam_index, detected_gap = find_return_to_start(recorded_xy)

    # The first sample and the late return sample observe the same physical
    # start line.  Their midpoint removes the small localization bias without
    # introducing a duplicate point at the loop boundary.
    seam_anchor = 0.5 * (recorded_xy[0] + recorded_xy[seam_index])
    closed_source = np.vstack(
        (seam_anchor, recorded_xy[1:seam_index], seam_anchor)
    )
    nominal_xy = resample_closed(closed_source, spacing_m)

    # The source was already smoothed. A compact periodic filter removes the
    # artificial seam bend and the few curvature spikes which exceed the
    # Gazebo Ackermann plugin's effective 0.464 rad central-steer limit. Five
    # passes have an approximately 11 cm standard deviation: small compared
    # with the lane width, while providing useful steering margin.
    for _ in range(PERIODIC_SMOOTHING_PASSES):
        nominal_xy = smooth_periodic_once(nominal_xy)
    nominal_xy = resample_closed(
        np.vstack((nominal_xy, nominal_xy[0])), spacing_m
    )
    yaw, curvature = periodic_geometry(nominal_xy)
    trajectory = np.column_stack((nominal_xy, yaw, curvature))

    report = {
        "source_points": int(len(recorded_xy)),
        "seam_source_index": int(seam_index),
        "detected_seam_gap_m": detected_gap,
        "removed_tail_points": int(len(recorded_xy) - seam_index - 1),
        "canonical_points": int(len(trajectory)),
        "canonical_length_m": float(
            np.sum(np.linalg.norm(np.roll(nominal_xy, -1, axis=0) - nominal_xy, axis=1))
        ),
        "canonical_spacing_m": float(
            np.mean(np.linalg.norm(np.roll(nominal_xy, -1, axis=0) - nominal_xy, axis=1))
        ),
        "smoothing_passes": PERIODIC_SMOOTHING_PASSES,
    }
    return trajectory, report


def save_csv_atomic(path: str, trajectory: np.ndarray) -> None:
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    descriptor, temporary_path = tempfile.mkstemp(
        prefix=".canonical_path_", suffix=".csv", dir=directory, text=True
    )
    try:
        with os.fdopen(
            descriptor, "w", encoding="utf-8", newline=""
        ) as stream:
            writer = csv.writer(stream, lineterminator="\n")
            writer.writerow(("x", "y", "theta"))
            for x, y, yaw in trajectory[:, :3]:
                writer.writerow((format(x, ".17g"), format(y, ".17g"), format(yaw, ".17g")))
        os.replace(temporary_path, path)
    except BaseException:
        try:
            os.unlink(temporary_path)
        except FileNotFoundError:
            pass
        raise


def save_npy_atomic(path: str, trajectory: np.ndarray) -> None:
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    descriptor, temporary_path = tempfile.mkstemp(
        prefix=".canonical_path_", suffix=".npy", dir=directory
    )
    os.close(descriptor)
    try:
        np.save(temporary_path, trajectory)
        os.replace(temporary_path, path)
    except BaseException:
        try:
            os.unlink(temporary_path)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, help="original ROSbot CSV recording")
    parser.add_argument("--csv-out", required=True, help="canonical ROSbot CSV")
    parser.add_argument("--npy-out", required=True, help="canonical QCar NPY")
    parser.add_argument("--spacing", type=float, default=DEFAULT_SPACING_M)
    args = parser.parse_args()

    source = load_recorded_csv(args.source)
    trajectory, report = build_canonical_path(source, args.spacing)
    save_csv_atomic(args.csv_out, trajectory)
    save_npy_atomic(args.npy_out, trajectory)

    # Verify text serialization did not make the two consumers diverge.
    csv_xy = load_recorded_csv(args.csv_out)
    npy_xy = np.load(args.npy_out)[:, :2]
    if not np.array_equal(csv_xy, npy_xy):
        raise RuntimeError("generated CSV and NPY x/y values are not identical")

    print(
        "[canonical_path] source={source_points} seam_index={seam_source_index} "
        "seam_gap={detected_seam_gap_m:.3f} m removed_tail={removed_tail_points}".format(
            **report
        )
    )
    print(
        "[canonical_path] points={canonical_points} closed_length="
        "{canonical_length_m:.3f} m spacing={canonical_spacing_m:.5f} m".format(
            **report
        )
    )
    print(f"[canonical_path] ROSbot CSV -> {args.csv_out}")
    print(f"[canonical_path] QCar NPY  -> {args.npy_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
